<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>chromia-cli-tools-parent</artifactId>
    <groupId>com.chromia.cli.tools</groupId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <modules>
        <module>chromia-cli-base</module>
        <module>chromia-cli-tools</module>
        <module>chromia-build-tools</module>
        <module>coverage-report-aggregate</module>
    </modules>

    <name>Chromia Cli Tools Parent</name>

<!--    <codegen.version>0.16.9</codegen.version>-->
<!--    <postchain.version>3.42.4</postchain.version>-->
<!--    <postchain.client.version>3.37.1</postchain.client.version>-->
<!--    <rell.version>0.14.14</rell.version>-->
<!--    <rell.dokka.version>0.2.19</rell.dokka.version>-->
<!--    <rell.toolbox.version>0.8.9</rell.toolbox.version>-->

    <properties>
        <revision>dev</revision>
        <codegen.version>0.16.12</codegen.version>
        <postchain.version>3.47.1</postchain.version>
        <postchain.client.version>3.38.0</postchain.client.version>
        <rell.version>0.15.0</rell.version>
        <rell.dokka.version>0.2.22</rell.dokka.version>
        <rell.toolbox.version>0.8.12</rell.toolbox.version>
        <eif.version>0.16.3</eif.version>
        <directory.chain.version>1.101.15</directory.chain.version>
        <directory.source>${project.build.directory}/directory-chain/src</directory.source>

        <jgit.version>7.2.1.202505142326-r</jgit.version>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <kotlin.version>2.3.0</kotlin.version>
        <kotlin.compiler.jvmTarget>21</kotlin.compiler.jvmTarget>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <kotlin.code.style>obsolete</kotlin.code.style>
        <project.build.outputTimestamp>10</project.build.outputTimestamp>

        <assembly.path>${project.basedir}/src/main/assembly/targz.xml</assembly.path>
        <image.platforms>linux/amd64,linux/arm64</image.platforms>
        <gitlab.registry>registry.gitlab.com/chromaway/core-tools/chromia-cli-tools</gitlab.registry>
        <detekt.report>xml:${project.parent.build.directory}/code-quality-reports/${project.artifactId}/detekt-report.xml</detekt.report>
        <detekt.config>${project.parent.basedir}/detekt.yml</detekt.config>
    </properties>

    <repositories>
        <repository>
            <id>chromia-parent</id>
            <name>Chromia parent GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/50818999/packages/maven</url>
        </repository>
        <repository>
            <id>postchain-chromia</id>
            <url>https://gitlab.com/api/v4/projects/33481005/packages/maven</url>
        </repository>
        <repository>
            <id>postchain</id>
            <name>Postchain GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/32294340/packages/maven</url>
        </repository>
        <repository>
            <id>postchain-client</id>
            <name>Postchain Client GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/46288950/packages/maven</url>
        </repository>
        <repository>
            <id>rellr</id>
            <name>Rell Runtime Registry</name>
            <url>https://gitlab.com/api/v4/projects/32802097/packages/maven</url>
        </repository>
        <repository>
            <id>rell-codegen</id>
            <name>Rell Codegen Registry</name>
            <url>https://gitlab.com/api/v4/projects/37660703/packages/maven</url>
        </repository>
        <repository>
            <id>rell-dokka</id>
            <name>Rell Dokka Plugin Registry</name>
            <url>https://gitlab.com/api/v4/projects/55009888/packages/maven</url>
        </repository>
        <repository>
            <id>postchain-eif</id>
            <name>Postchain EIF Gtx module Registry</name>
            <url>https://gitlab.com/api/v4/projects/36768178/packages/maven</url>
        </repository>
        <repository>
            <id>rell-toolbox</id>
            <name>Rell Toolbox</name>
            <url>https://gitlab.com/api/v4/projects/51303085/packages/maven</url>
        </repository>
        <repository>
            <id>mavenCentral</id>
            <url>https://repo1.maven.org/maven2/</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>rell-maven</id>
            <url>https://gitlab.com/api/v4/projects/37668820/packages/maven</url>
        </pluginRepository>
        <pluginRepository>
            <id>kotlin-bcv-maven-plugin</id>
            <url>https://gitlab.com/api/v4/projects/64479054/packages/maven</url>
        </pluginRepository>
    </pluginRepositories>
    <distributionManagement>
        <repository>
            <id>gitlab-maven</id>
            <url>https://gitlab.com/api/v4/projects/64941451/packages/maven</url>
        </repository>
    </distributionManagement>

    <build>
        <sourceDirectory>src/main/kotlin</sourceDirectory>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.2.2</version>
                    <configuration>
                        <archive>
                            <manifest>
                                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                            </manifest>
                        </archive>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>net.postchain.rell</groupId>
                    <artifactId>rell-maven-plugin</artifactId>
                    <version>0.16.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <version>3.2.0</version>
                </plugin>
                <plugin>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-maven-plugin</artifactId>
                    <version>${kotlin.version}</version>
                    <configuration>
                        <args>
                            <arg>-Xannotation-default-target=first-only</arg> <!-- Needed to avoid warnings in the generated Rell client in Kotlin 2.2+ -->
                        </args>
                    </configuration>
                    <executions>
                        <execution>
                            <id>compile</id>
                            <phase>compile</phase>
                            <goals>
                                <goal>compile</goal>
                            </goals>
                            <configuration>
                                <sourceDirs>
                                    <sourceDir>${project.basedir}/src/main/kotlin</sourceDir>
                                </sourceDirs>
                            </configuration>
                        </execution>
                        <execution>
                            <id>test-compile</id>
                            <phase>test-compile</phase>
                            <goals>
                                <goal>test-compile</goal>
                            </goals>
                            <configuration>
                                <sourceDirs>
                                    <sourceDir>${project.basedir}/src/test/kotlin</sourceDir>
                                </sourceDirs>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.10.1</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.1.2</version>
                    <configuration>
                        <workingDirectory>${project.build.directory}/test</workingDirectory>
                        <excludes>
                            <exclude>**/*IT.java</exclude>
                            <exclude>**/*SlowIntegrationTest.java</exclude>
                        </excludes>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>3.1.2</version>
                    <configuration>
                        <environmentVariables>
                            <DIST_EXECUTABLE>
                                ${project.build.directory}/${project.artifactId}-${project.version}-dist/bin/chr
                            </DIST_EXECUTABLE>
                            <!--suppress UnresolvedMavenProperty -->
                            <JAVA_ARGS>${argLine}</JAVA_ARGS>
                            <PROJECT_VERSION>${project.version}</PROJECT_VERSION>
                        </environmentVariables>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>integration-test</goal>
                                <goal>verify</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>pl.project13.maven</groupId>
                    <artifactId>git-commit-id-plugin</artifactId>
                    <version>4.0.0</version>
                    <executions>
                        <execution>
                            <id>get-the-git-infos</id>
                            <goals>
                                <goal>revision</goal>
                            </goals>
                            <phase>initialize</phase>
                        </execution>
                    </executions>
                    <configuration>
                        <useNativeGit>true</useNativeGit> <!-- git worktree does not work with JGit implementation -->
                        <includeOnlyProperties>
                            <includeOnlyProperty>^git\.commit\.time$</includeOnlyProperty>
                        </includeOnlyProperties>
                        <dateFormatTimeZone>UTC</dateFormatTimeZone>
                        <dateFormat>yyyy-MM-dd'T'HH:mm:ssX</dateFormat>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>com.google.cloud.tools</groupId>
                    <artifactId>jib-maven-plugin</artifactId>
                    <version>3.3.2</version>
                </plugin>
                <plugin>
                    <groupId>org.owasp</groupId>
                    <artifactId>dependency-check-maven</artifactId>
                    <version>12.1.5</version>
                    <configuration>
                        <prettyPrint>true</prettyPrint>
                        <failBuildOnAnyVulnerability>true</failBuildOnAnyVulnerability>
                        <assemblyAnalyzerEnabled>false</assemblyAnalyzerEnabled>
                        <yarnAuditAnalyzerEnabled>false</yarnAuditAnalyzerEnabled>
                        <suppressionFiles>
                            <suppressionFile>
                                https://gitlab.com/chromaway/chromia-parent/-/raw/dev/common-dependencies-suppression.xml?ref_type=heads
                            </suppressionFile>
                            <suppressionFile>dependencies-suppression.xml</suppressionFile>
                        </suppressionFiles>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>com.chromaway</groupId>
                    <artifactId>kotlin-bcv-maven-plugin</artifactId>
                    <version>0.2.0</version>
                    <configuration>
                        <skip>true</skip>
                    </configuration>
                    <executions>
                        <execution>
                            <id>check</id>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>com.github.ozsie</groupId>
                    <artifactId>detekt-maven-plugin</artifactId>
                    <version>1.23.7</version>
                    <executions>
                        <execution>
                            <phase>verify</phase>
                            <goals><goal>check</goal></goals>
                            <configuration>
                                <config>${detekt.config}</config>
                                <report>
                                    <report>${detekt.report}</report>
                                </report>
                                <baseline>${project.basedir}/baseline.xml</baseline>
                            </configuration>
                        </execution>
                    </executions>
                    <dependencies>
                        <dependency>
                            <groupId>io.gitlab.arturbosch.detekt</groupId>
                            <artifactId>detekt-formatting</artifactId>
                            <version>1.23.7</version>
                        </dependency>
                    </dependencies>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>1.4.1</version>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-bom</artifactId>
                <version>${kotlin.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <!-- Temporariliy downgrade jackson version due to incompatibility in dokka -->
            <dependency>
                <groupId>com.fasterxml.jackson</groupId>
                <artifactId>jackson-bom</artifactId>
                <version>2.15.3</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>net.postchain</groupId>
                <artifactId>postchain</artifactId>
                <version>${postchain.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell</artifactId>
                <version>${rell.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>5.9.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.chromia.cli.tools</groupId>
                <artifactId>chromia-cli-base</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.chromia.cli.tools</groupId>
                <artifactId>chromia-cli-tools</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.chromia.cli.tools</groupId>
                <artifactId>chromia-build-tools</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.chromia.cli.tools</groupId>
                <artifactId>chromia-build-tools</artifactId>
                <version>${project.version}</version>
                <type>test-jar</type>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-api-gtx</artifactId>
                <version>${rell.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-api-shell</artifactId>
                <version>${rell.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-api-base</artifactId>
                <version>${rell.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.client</groupId>
                <artifactId>postchain-client</artifactId>
                <version>${postchain.client.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.client</groupId>
                <artifactId>chromia-client</artifactId>
                <version>${postchain.client.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.client</groupId>
                <artifactId>ft4-client</artifactId>
                <version>${postchain.client.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain</groupId>
                <artifactId>postchain-spi</artifactId>
                <version>${postchain.version}</version>
            </dependency>
            <!-- TODO try to get rid of postchain-base dependency -->
            <dependency>
                <groupId>net.postchain</groupId>
                <artifactId>postchain-base</artifactId>
                <version>${postchain.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>net.postchain</groupId>
                        <artifactId>postchain-admin-service</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>io.grpc</groupId>
                        <artifactId>grpc-api</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>codegen-kotlin</artifactId>
                <version>${codegen.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>codegen-mermaid</artifactId>
                <version>${codegen.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>codegen-typescript</artifactId>
                <version>${codegen.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>codegen-javascript</artifactId>
                <version>${codegen.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>codegen-python</artifactId>
                <version>${codegen.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell</groupId>
                <artifactId>codegen</artifactId>
                <version>${codegen.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell.toolbox</groupId>
                <artifactId>code-quality</artifactId>
                <version>${rell.toolbox.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell.toolbox</groupId>
                <artifactId>indexer</artifactId>
                <version>${rell.toolbox.version}</version>
            </dependency>
            <dependency>
                <groupId>net.postchain.rell.toolbox</groupId>
                <artifactId>common</artifactId>
                <version>${rell.toolbox.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jgit</groupId>
                <artifactId>org.eclipse.jgit</artifactId>
                <version>${jgit.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jgit</groupId>
                <artifactId>org.eclipse.jgit.ssh.apache</artifactId>
                <version>${jgit.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jgit</groupId>
                <artifactId>org.eclipse.jgit.ssh.apache.agent</artifactId>
                <version>${jgit.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.kotlinx</groupId>
                <artifactId>kotlinx-coroutines-core-jvm</artifactId>
                <version>1.6.4</version>
            </dependency>
            <dependency>
                <groupId>com.github.ajalt.clikt</groupId>
                <artifactId>clikt-jvm</artifactId>
                <version>5.1.0</version>
            </dependency>
            <dependency>
                <groupId>com.github.ajalt.clikt</groupId>
                <artifactId>clikt-markdown-jvm</artifactId>
                <version>5.1.0</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains</groupId>
                <artifactId>markdown-jvm</artifactId>
                <version>0.7.3</version>
            </dependency>
            <dependency>
                <groupId>com.github.ajalt.mordant</groupId>
                <artifactId>mordant-jvm-jna-jvm</artifactId>
                <version>3.0.2</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-slf4j-impl</artifactId>
                <version>2.19.0</version>
                <scope>runtime</scope>
            </dependency>
            <dependency>
                <groupId>dev.forkhandles</groupId>
                <artifactId>result4k</artifactId>
                <version>2.4.0.0</version>
            </dependency>
            <dependency>
                <groupId>org.http4k</groupId>
                <artifactId>http4k-format-jackson</artifactId>
                <version>4.34.0.4</version>
            </dependency>
            <dependency>
                <groupId>org.redundent</groupId>
                <artifactId>kotlin-xml-builder</artifactId>
                <version>1.9.0</version>
            </dependency>
            <dependency>
                <groupId>net.pwall.json</groupId>
                <artifactId>json-kotlin-schema</artifactId>
                <version>0.44</version>
            </dependency>
            <dependency>
                <groupId>org.apache.tika</groupId>
                <artifactId>tika-core</artifactId>
                <version>3.2.2</version>
            </dependency>

            <dependency>
                <groupId>org.webjars.npm</groupId>
                <artifactId>ethers</artifactId>
                <version>6.13.1</version>
            </dependency>

            <!-- Needed by postchain-client -->
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>2.17.0</version>
            </dependency>

            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>5.7.0</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito.kotlin</groupId>
                <artifactId>mockito-kotlin</artifactId>
                <version>5.2.1</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-inline</artifactId>
                <version>5.2.0</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>uk.org.webcompere</groupId>
                <artifactId>system-stubs-jupiter</artifactId>
                <version>2.1.6</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.willowtreeapps.assertk</groupId>
            <artifactId>assertk-jvm</artifactId>
            <version>0.26.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>ci</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-plugin</artifactId>
                        <configuration>
                            <args>
                                <arg>-Xannotation-default-target=first-only</arg> <!-- Needed to avoid warnings in the generated Rell client in Kotlin 2.2+ -->
                                <arg>-Werror</arg>
                            </args>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>coverage</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.jacoco</groupId>
                        <artifactId>jacoco-maven-plugin</artifactId>
                        <version>0.8.10</version>
                        <configuration>
                            <excludes>
                                <!-- Generated sources -->
                                <exclude>com/chromia/directory1/**</exclude>
                                <!-- Inner classes of ReplCommand (Dummy OutputCannelFactory -->
                                <exclude>com/chromia/cli/ReplCommand$*</exclude>
                                <!-- Copied from mordant -->
                                <exclude>com/chromia/cli/tools/mordant/*</exclude>
                            </excludes>
                        </configuration>
                        <executions>
                            <execution>
                                <id>default-prepare-agent</id>
                                <goals>
                                    <goal>prepare-agent</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>default-prepare-agent-integration</id>
                                <goals>
                                    <goal>prepare-agent-integration</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>default-report</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>report</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>default-report-integration</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>report-integration</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>artifact</id>
            <activation>
                <activeByDefault>true</activeByDefault>
                <property>
                    <name>!local</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <inherited>false</inherited>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-scm-plugin</artifactId>
                        <version>1.11.2</version>
                        <executions>
                            <execution>
                                <id>d1-resources</id>
                                <phase>generate-sources</phase>
                                <goals>
                                    <goal>checkout</goal>
                                </goals>
                                <configuration>
                                    <connectionUrl>scm:git:https://gitlab.com/chromaway/core/directory-chain.git
                                    </connectionUrl>
                                    <checkoutDirectory>${project.build.directory}/directory-chain
                                    </checkoutDirectory>
                                    <scmVersion>${directory.chain.version}</scmVersion>
                                    <scmVersionType>tag</scmVersionType>
                                    <skipCheckoutIfExists>true</skipCheckoutIfExists>
                                </configuration>
                            </execution>
                            <execution>
                                <id>library-chain-checkout</id>
                                <phase>generate-sources</phase>
                                <goals>
                                    <goal>checkout</goal>
                                </goals>
                                <configuration>
                                    <connectionUrl>scm:git:https://bitbucket.org/chromawallet/library-chain.git
                                    </connectionUrl>
                                    <checkoutDirectory>${project.build.directory}/library-chain
                                    </checkoutDirectory>
                                    <scmVersion>main</scmVersion>
                                    <scmVersionType>branch</scmVersionType>
                                    <skipCheckoutIfExists>true</skipCheckoutIfExists>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>local</id>
            <activation>
                <property>
                    <name>local</name>
                </property>
            </activation>
            <properties>
                <directory.source>${project.basedir}/../../directory-chain/src</directory.source>
                <library-chain.source>${project.basedir}/../../library-chain/src</library-chain.source>
            </properties>
        </profile>
    </profiles>

</project>
