<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.chromia.cli</groupId>
        <artifactId>chromia-cli-parent</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>chromia-build-tools</artifactId>
    <version>${revision}</version>
    <packaging>jar</packaging>

    <name>Chromia Build Tools</name>

    <properties>
        <revision>dev</revision>
        <directory.source>${project.parent.build.directory}/directory-chain/src</directory.source>
        <directory.config>${directory.source}/../chromia.yml</directory.config>
    </properties>


    <build>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-maven-plugin</artifactId>
                <configuration>
                    <source>${directory.source}</source>
                </configuration>
                <executions>
                    <execution>
                        <id>rell-client-gen</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>rell-install</goal>
                            <goal>rell-generate-client</goal>
                        </goals>
                        <configuration>
                            <packageName>com.chromia.directory1</packageName>
                            <mainModule>
                                version,proposal_blockchain,common.queries,anchoring_chain_common,economy_chain_test,economy_chain_in_directory_chain
                            </mainModule>
                            <configPath>${directory.config}</configPath>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.chromaway</groupId>
                <artifactId>kotlin-bcv-maven-plugin</artifactId>
                <configuration>
                    <skip>false</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-api-base</artifactId>
            <version>${rell.version}</version>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-gtx</artifactId>
            <version>${rell.version}</version>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-base</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-gtv</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-gtv-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-web-static</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>chromia-client</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.client</groupId>
            <artifactId>postchain-client</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>codegen</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jgit</groupId>
            <artifactId>org.eclipse.jgit</artifactId>
        </dependency>
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
        </dependency>
        <dependency>
            <groupId>net.pwall.json</groupId>
            <artifactId>json-kotlin-schema</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jgit</groupId>
            <artifactId>org.eclipse.jgit.ssh.apache</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jgit</groupId>
            <artifactId>org.eclipse.jgit.ssh.apache.agent</artifactId>
        </dependency>
        <dependency>
            <groupId>org.redundent</groupId>
            <artifactId>kotlin-xml-builder</artifactId>
        </dependency>
        <dependency>
          <groupId>org.apache.tika</groupId>
          <artifactId>tika-core</artifactId>
        </dependency>

        <dependency>
            <groupId>uk.org.webcompere</groupId>
            <artifactId>system-stubs-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
